dist: xenial
language: scala
addons:
  apt:
    update: true
scala:
  - 2.11.12
  - 2.12.10
  - 2.13.1
jdk:
  - openjdk8
script:
  - sbt ++${TRAVIS_SCALA_VERSION}! coreJVM/test coreJS/test

matrix:
  include:
    - scala: 0.21.0-RC1
      script: sbt ++$TRAVIS_SCALA_VERSION coreJVM/test

    - scala: 2.11.12
      before_script:
        - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
      sudo: required
      script: sbt ++$TRAVIS_SCALA_VERSION! coreNative/test

    - scala: 2.11.12
      env: SCALANATIVE_VERSION="0.4.0-M2"
      before_script:
        - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
      sudo: required
      script: sbt ++$TRAVIS_SCALA_VERSION! coreNative/test

    - scala: 2.11.12
      env: SCALAJS_VERSION="0.6.31"
      script: sbt ++$TRAVIS_SCALA_VERSION! coreJS/test

    - scala: 2.12.10
      env: SCALAJS_VERSION="0.6.31"
      script: sbt ++$TRAVIS_SCALA_VERSION! coreJS/test

    - scala: 2.13.1
      env: SCALAJS_VERSION="0.6.31"
      script: sbt ++$TRAVIS_SCALA_VERSION! coreJS/test
